export const outputAliases = [
  ["en.html", "en/index.html"],
  ["share.html", "share/index.html"],
  ["en/share.html", "en/share/index.html"],
  ["terms.html", "terms/index.html"],
  ["privacy.html", "privacy/index.html"],
  ["en/terms.html", "en/terms/index.html"],
  ["en/privacy.html", "en/privacy/index.html"],
];

export const requiredOutputFiles = [
  "index.html",
  "en.html",
  "en/index.html",
  "share.html",
  "share/index.html",
  "en/share.html",
  "en/share/index.html",
  "terms.html",
  "terms/index.html",
  "privacy.html",
  "privacy/index.html",
  "en/terms.html",
  "en/terms/index.html",
  "en/privacy.html",
  "en/privacy/index.html",
  "404.html",
  ".nojekyll",
  "robots.txt",
  "sitemap.xml",
  "media/social/tessa-social.png",
  "media/brand/tessa-wallet-mark.png",
  "icons/favicon.ico",
  "icons/favicon-16x16.png",
  "icons/favicon-32x32.png",
  "icons/apple-touch-icon.png",
  "icons/android-chrome-192x192.png",
  "icons/android-chrome-384x384.png",
  "icons/mstile-150x150.png",
  "icons/site.webmanifest",
  "icons/browserconfig.xml",
];
